version: "3.7"
services:
  identityserver: 
    image: identityserver
  
  identityserver-api:
    image: identityserver-api
    depends_on:
      - "identityserver"

  identityserver-client:
    image: identityserver-client
    depends_on:
      - "identityserver"
      - "identityserver-api"
